cwlVersion: v1.0
class: CommandLineTool
id: gatk_gatherbamfiles
requirements:
  - class: ShellCommandRequirement
  - class: InlineJavascriptRequirement
  - class: DockerRequirement
    dockerPull: <docker>
  - class: ResourceRequirement
    ramMin: 3500
baseCommand: [java, -Xms2000m, -jar, /picard.jar]
arguments:
  - position: 0
    shellQuote: false
    valueFrom: >-
      -Dsamjdk.compression_level=$(inputs.compression_level)
      OUTPUT = $(input.output_bam)
      CREATE_INDEX = true
      CREATE_MD5_FILE = true
inputs:
  input_bam: array
    items: File
    inputBinding:
      prefix: INPUT=
  output_Bam: string
  compression_level: int
outputs:
  output_bam:
    type: File
    outputBinding:
      glob: "*.bam"
    secondaryFile:[^.bai,^.md5]
